### PR TITLE
Force lint

### LINKED ISSUE #48: Fix inconsistent indentation
pylint tells me the autogenerated files are mostly using 2-space ident.
This issue is to reformat all files to 4-space indentation.

### PR DESCRIPTION
**Pull request by avishayp**
### in this PR
 * Complete #47 (for now) by adding `pylint` to workflow
 * Fix #48 by autopepping codebase (excluding `__init__.py` files)

This should be a minimal-risk PR, bar the options that workflow-enforced linting will annoy future contributors.

### CODE REVIEW

**Comment by avishayp** [comment]
@DentonGentry am ready to take something more interesting now.

**Comment by DentonGentry** [comment]
ui.tests.test_vega is failing the pylint check in continuous integration, would prefer not to merge if it will make master fail tests.

**Comment by avishayp** [comment]
Fixed.
@DentonGentry have you applied workflow to `master` only be design?

**Comment by DentonGentry** [comment]
"have you applied workflow to `master` only by-design?"

Yes, though maybe not entirely thought through. I was looking at my own use, where pushing to a branch would start running the workflow, and then making the pull_request would begin running the workflow a second time in parallel. That seemed silly.

However I think I see the issue now, that the github workflow might not be run at all on people's forks of the workspace, if they're making the pull request from a feature branch in their fork. They might be running stuff on their own systems, but the first time the github action would run is after the pull_request. Is that the concern?

https://github.com/ProjectDrawdown/solutions/pull/65 sets it to run the workflow on push to any branch and on pull request. It is, as expected, currently running the workflow twice for the push and for the pull_request.

**Comment by DentonGentry** [comment]
"am ready to take something more interesting now."

What are you particularly interested in?

If you found this by way of interest in the Drawdown solutions, there may be some things I could suggest on solutions of particular interest. For example, Food Waste, Plant-rich Diet, Family Planning, and Women and Girls have not been started as they differ more substantially from the rest of the solution models.

**Comment by avishayp** [comment]
> Is that the concern?

My current concern is my PR broke the tests but I didn't get the notification because it's not my repo.
My settings are "notify on failure only", so I've assumed it passed and called it the day. Pretty subtle.

**Comment by avishayp** [comment]
> What are you particularly interested in?

Food Waste may be a good candidate. Also #6

**Pull request merged**
