### PR TITLE
Optimise models with numpy / pandas

### PR DESCRIPTION
**Pull request by klemag**
This should provide some performance improvement. It's mostly updating methods that were slow to leverage more of numpy / broadcasting and when necessary pandas.

I've timed it on all solutions:

## Before
```
Time solution afforestation:
	* Total (2 scenarios): 3.688269 s
	* Average: 1.844134 s
Time solution airplanes:
	* Total (3 scenarios): 3.678080 s
	* Average: 1.226027 s
Time solution altcement:
	* Total (1 scenarios): 1.711526 s
	* Average: 1.711526 s
Time solution bamboo:
	* Total (3 scenarios): 4.814030 s
	* Average: 1.604677 s
Time solution bikeinfrastructure:
	* Total (3 scenarios): 2.947950 s
	* Average: 0.982650 s
Time solution biochar:
	* Total (3 scenarios): 4.616133 s
	* Average: 1.538711 s
Time solution biogas:
	* Total (9 scenarios): 23.547891 s
	* Average: 2.616432 s
Time solution biogas_small:
	* Total (3 scenarios): 5.42246 s
	* Average: 1.680749 s
Time solution biomass:
	* Total (6 scenarios): 14.373217 s
	* Average: 2.395536 s
Time solution bioplastic:
	* Total (3 scenarios): 3.725966 s
	* Average: 1.241989 s
Time solution bottomtrawling:
	* Total (1 scenarios): 1.699635 s
	* Average: 1.699635 s
Time solution buildingautomation:
	* Total (3 scenarios): 6.392908 s
	* Average: 2.130969 s
Time solution carpooling:
	* Total (3 scenarios): 4.983120 s
	* Average: 1.661040 s
Time solution cars:
	* Total (3 scenarios): 4.392694 s
	* Average: 1.464231 s
Time solution composting:
	* Total (3 scenarios): 6.131585 s
	* Average: 2.43862 s
Time solution concentratedsolar:
	* Total (6 scenarios): 15.612693 s
	* Average: 2.602116 s
Time solution conservationagriculture:
	* Total (3 scenarios): 3.979998 s
	* Average: 1.326666 s
Time solution coolroofs:
	* Total (3 scenarios): 7.909436 s
	* Average: 2.636479 s
Time solution districtheating:
	* Total (3 scenarios): 4.705325 s
	* Average: 1.568442 s
Time solution electricbikes:
	* Total (3 scenarios): 3.901257 s
	* Average: 1.300419 s
Time solution electricvehicles:
	* Total (3 scenarios): 4.216423 s
	* Average: 1.405474 s
Time solution farmlandrestoration:
	* Total (3 scenarios): 3.921548 s
	* Average: 1.307183 s
Time solution forestprotection:
	* Total (3 scenarios): 8.479509 s
	* Average: 2.826503 s
Time solution geothermal:
	* Total (3 scenarios): 4.649135 s
	* Average: 1.549712 s
Time solution greenroofs:
	* Total (3 scenarios): 7.819896 s
	* Average: 2.606632 s
Time solution heatpumps:
	* Total (3 scenarios): 5.285470 s
	* Average: 1.761823 s
Time solution highspeedrail:
	* Total (3 scenarios): 4.514599 s
	* Average: 1.504866 s
Time solution improvedcookstoves:
	* Total (3 scenarios): 5.700633 s
	* Average: 1.900211 s
Time solution improvedrice:
	* Total (3 scenarios): 4.24 s
	* Average: 1.333341 s
Time solution indigenouspeoplesland:
	* Total (3 scenarios): 8.792485 s
	* Average: 2.930828 s
Time solution instreamhydro:
	* Total (3 scenarios): 4.687500 s
	* Average: 1.562500 s
Time solution insulation:
	* Total (3 scenarios): 2.947330 s
	* Average: 0.982443 s
Time solution irrigationefficiency:
	* Total (3 scenarios): 3.873686 s
	* Average: 1.291229 s
Time solution landfillmethane:
	* Total (8 scenarios): 15.124324 s
	* Average: 1.890540 s
Time solution leds_commercial:
	* Total (3 scenarios): 7.67502 s
	* Average: 2.355834 s
Time solution leds_residential:
	* Total (3 scenarios): 5.984 s
	* Average: 1.666995 s
Time solution managedgrazing:
	* Total (3 scenarios): 3.933509 s
	* Average: 1.311170 s
Time solution masstransit:
	* Total (3 scenarios): 4.395451 s
	* Average: 1.465150 s
Time solution microwind:
	* Total (6 scenarios): 9.956642 s
	* Average: 1.659440 s
Time solution multistrataagroforestry:
	* Total (3 scenarios): 3.947965 s
	* Average: 1.315988 s
Time solution nuclear:
	* Total (5 scenarios): 13.112223 s
	* Average: 2.622445 s
Time solution nutrientmanagement:
	* Total (3 scenarios): 4.94022 s
	* Average: 1.364674 s
Time solution offshorewind:
	* Total (4 scenarios): 8.420911 s
	* Average: 2.105228 s
Time solution onshorewind:
	* Total (4 scenarios): 10.987865 s
	* Average: 2.746966 s
Time solution peatlands:
	* Total (3 scenarios): 8.697335 s
	* Average: 2.899112 s
Time solution perennialbioenergy:
	* Total (3 scenarios): 4.91455 s
	* Average: 1.363818 s
Time solution recycledpaper:
	* Total (3 scenarios): 6.487023 s
	* Average: 2.162341 s
Time solution refrigerants:
	* Total (2 scenarios): 3.285976 s
	* Average: 1.642988 s
Time solution regenerativeagriculture:
	* Total (3 scenarios): 4.74264 s
	* Average: 1.358088 s
Time solution riceintensification:
	* Total (3 scenarios): 4.24953 s
	* Average: 1.341651 s
Time solution ships:
	* Total (3 scenarios): 4.721079 s
	* Average: 1.573693 s
Time solution silvopasture:
	* Total (3 scenarios): 4.942136 s
	* Average: 1.647379 s
Time solution smartglass:
	* Total (3 scenarios): 3.585030 s
	* Average: 1.195010 s
Time solution smartthermostats:
	* Total (3 scenarios): 4.750904 s
	* Average: 1.583635 s
Time solution solarhotwater:
	* Total (3 scenarios): 6.194523 s
	* Average: 2.64841 s
Time solution solarpvroof:
	* Total (4 scenarios): 6.504880 s
	* Average: 1.626220 s
Time solution solarpvutil:
	* Total (3 scenarios): 4.895698 s
	* Average: 1.631899 s
Time solution telepresence:
	* Total (3 scenarios): 3.851909 s
	* Average: 1.283970 s
Time solution temperateforests:
	* Total (6 scenarios): 16.661754 s
	* Average: 2.776959 s
Time solution trains:
	* Total (3 scenarios): 3.39145 s
	* Average: 1.13048 s
Time solution treeintercropping:
	* Total (3 scenarios): 4.259127 s
	* Average: 1.419709 s
Time solution tropicalforests:
	* Total (6 scenarios): 15.749835 s
	* Average: 2.624972 s
Time solution tropicaltreestaples:
	* Total (3 scenarios): 5.802771 s
	* Average: 1.934257 s
Time solution trucks:
	* Total (3 scenarios): 2.776306 s
	* Average: 0.925435 s
Time solution walkablecities:
	* Total (3 scenarios): 4.506651 s
	* Average: 1.502217 s
Time solution wastetoenergy:
	* Total (3 scenarios): 9.267505 s
	* Average: 3.89168 s
Time solution waterdistribution:
	* Total (3 scenarios): 4.316300 s
	* Average: 1.438767 s
Time solution waterefficiency:
	* Total (3 scenarios): 4.263087 s
	* Average: 1.421029 s
Time solution waveandtidal:
	* Total (3 scenarios): 4.841436 s
	* Average: 1.613812 s
Time solution womensmallholders:
	* Total (3 scenarios): 3.932547 s
	* Average: 1.310849 s
```

## After
```
Time solution afforestation:
	* Total (2 scenarios): 1.477308 s
	* Average: 0.738654 s
Time solution airplanes:
	* Total (3 scenarios): 1.172622 s
	* Average: 0.390874 s
Time solution altcement:
	* Total (1 scenarios): 0.503195 s
	* Average: 0.503195 s
Time solution bamboo:
	* Total (3 scenarios): 1.573802 s
	* Average: 0.524601 s
Time solution bikeinfrastructure:
	* Total (3 scenarios): 1.59128 s
	* Average: 0.353043 s
Time solution biochar:
	* Total (3 scenarios): 1.575501 s
	* Average: 0.525167 s
Time solution biogas:
	* Total (9 scenarios): 11.598657 s
	* Average: 1.288740 s
Time solution biogas_small:
	* Total (3 scenarios): 2.496164 s
	* Average: 0.832055 s
Time solution biomass:
	* Total (6 scenarios): 6.188958 s
	* Average: 1.31493 s
Time solution bioplastic:
	* Total (3 scenarios): 1.286894 s
	* Average: 0.428965 s
Time solution bottomtrawling:
	* Total (1 scenarios): 0.488237 s
	* Average: 0.488237 s
Time solution buildingautomation:
	* Total (3 scenarios): 2.109644 s
	* Average: 0.703215 s
Time solution carpooling:
	* Total (3 scenarios): 1.642422 s
	* Average: 0.547474 s
Time solution cars:
	* Total (3 scenarios): 1.852925 s
	* Average: 0.617642 s
Time solution composting:
	* Total (3 scenarios): 2.457454 s
	* Average: 0.819151 s
Time solution concentratedsolar:
	* Total (6 scenarios): 7.327251 s
	* Average: 1.221208 s
Time solution conservationagriculture:
	* Total (3 scenarios): 1.723542 s
	* Average: 0.574514 s
Time solution coolroofs:
	* Total (3 scenarios): 5.312166 s
	* Average: 1.770722 s
Time solution districtheating:
	* Total (3 scenarios): 2.2538 s
	* Average: 0.667513 s
Time solution electricbikes:
	* Total (3 scenarios): 1.393177 s
	* Average: 0.464392 s
Time solution electricvehicles:
	* Total (3 scenarios): 1.740706 s
	* Average: 0.580235 s
Time solution farmlandrestoration:
	* Total (3 scenarios): 1.539952 s
	* Average: 0.513317 s
Time solution forestprotection:
	* Total (3 scenarios): 5.132091 s
	* Average: 1.710697 s
Time solution geothermal:
	* Total (3 scenarios): 2.230474 s
	* Average: 0.743491 s
Time solution greenroofs:
	* Total (3 scenarios): 5.122252 s
	* Average: 1.707417 s
Time solution heatpumps:
	* Total (3 scenarios): 2.869528 s
	* Average: 0.956509 s
Time solution highspeedrail:
	* Total (3 scenarios): 1.202273 s
	* Average: 0.400758 s
Time solution improvedcookstoves:
	* Total (3 scenarios): 2.380999 s
	* Average: 0.793666 s
Time solution improvedrice:
	* Total (3 scenarios): 1.644108 s
	* Average: 0.548036 s
Time solution indigenouspeoplesland:
	* Total (3 scenarios): 5.122876 s
	* Average: 1.707625 s
Time solution instreamhydro:
	* Total (3 scenarios): 2.232717 s
	* Average: 0.744239 s
Time solution insulation:
	* Total (3 scenarios): 1.93873 s
	* Average: 0.364624 s
Time solution irrigationefficiency:
	* Total (3 scenarios): 1.629171 s
	* Average: 0.543057 s
Time solution landfillmethane:
	* Total (8 scenarios): 6.789640 s
	* Average: 0.848705 s
Time solution leds_commercial:
	* Total (3 scenarios): 2.805186 s
	* Average: 0.935062 s
Time solution leds_residential:
	* Total (3 scenarios): 1.186031 s
	* Average: 0.395344 s
Time solution managedgrazing:
	* Total (3 scenarios): 1.639785 s
	* Average: 0.546595 s
Time solution masstransit:
	* Total (3 scenarios): 1.479736 s
	* Average: 0.493245 s
Time solution microwind:
	* Total (6 scenarios): 4.332990 s
	* Average: 0.722165 s
Time solution multistrataagroforestry:
	* Total (3 scenarios): 1.563902 s
	* Average: 0.521301 s
Time solution nuclear:
	* Total (5 scenarios): 6.589643 s
	* Average: 1.317929 s
Time solution nutrientmanagement:
	* Total (3 scenarios): 1.646794 s
	* Average: 0.548931 s
Time solution offshorewind:
	* Total (4 scenarios): 3.737067 s
	* Average: 0.934267 s
Time solution onshorewind:
	* Total (4 scenarios): 5.26028 s
	* Average: 1.256507 s
Time solution peatlands:
	* Total (3 scenarios): 5.314915 s
	* Average: 1.771638 s
Time solution perennialbioenergy:
	* Total (3 scenarios): 1.694944 s
	* Average: 0.564981 s
Time solution recycledpaper:
	* Total (3 scenarios): 2.172873 s
	* Average: 0.724291 s
Time solution refrigerants:
	* Total (2 scenarios): 1.132605 s
	* Average: 0.566302 s
Time solution regenerativeagriculture:
	* Total (3 scenarios): 1.654070 s
	* Average: 0.551357 s
Time solution riceintensification:
	* Total (3 scenarios): 1.795140 s
	* Average: 0.598380 s
Time solution ships:
	* Total (3 scenarios): 1.295054 s
	* Average: 0.431685 s
Time solution silvopasture:
	* Total (3 scenarios): 1.607696 s
	* Average: 0.535899 s
Time solution smartglass:
	* Total (3 scenarios): 1.44871 s
	* Average: 0.348290 s
Time solution smartthermostats:
	* Total (3 scenarios): 1.332354 s
	* Average: 0.444118 s
Time solution solarhotwater:
	* Total (3 scenarios): 2.527354 s
	* Average: 0.842451 s
Time solution solarpvroof:
	* Total (4 scenarios): 2.870013 s
	* Average: 0.717503 s
Time solution solarpvutil:
	* Total (3 scenarios): 2.149663 s
	* Average: 0.716554 s
Time solution telepresence:
	* Total (3 scenarios): 1.416322 s
	* Average: 0.472107 s
Time solution temperateforests:
	* Total (6 scenarios): 10.693043 s
	* Average: 1.782174 s
Time solution trains:
	* Total (3 scenarios): 1.101369 s
	* Average: 0.367123 s
Time solution treeintercropping:
	* Total (3 scenarios): 1.527848 s
	* Average: 0.509283 s
Time solution tropicalforests:
	* Total (6 scenarios): 11.45029 s
	* Average: 1.840838 s
Time solution tropicaltreestaples:
	* Total (3 scenarios): 3.475749 s
	* Average: 1.158583 s
Time solution trucks:
	* Total (3 scenarios): 1.123198 s
	* Average: 0.374399 s
Time solution walkablecities:
	* Total (3 scenarios): 1.880533 s
	* Average: 0.626844 s
Time solution wastetoenergy:
	* Total (3 scenarios): 3.646973 s
	* Average: 1.215658 s
Time solution waterdistribution:
	* Total (3 scenarios): 1.277828 s
	* Average: 0.425943 s
Time solution waterefficiency:
	* Total (3 scenarios): 1.269264 s
	* Average: 0.423088 s
Time solution waveandtidal:
	* Total (3 scenarios): 2.127793 s
	* Average: 0.709264 s
Time solution womensmallholders:
	* Total (3 scenarios): 1.559969 s
	* Average: 0.519990 s
```

Note: In helperstables.py, we were using pd.combine to combine our adoption dataframe with pds_adoption_limits and apply a threshold on it. We are replacing missing values in pdfs_adoption_limits by 0 so that should cap things at 0 when the threshold is missing. However, when the whole year is missing from pds_adoption_limits, this has the effect of not applying the threshold at all. To replicate that behaviour I used `self.pds_adoption_limits.reindex(adoption.index,                                                                        fill_value=np.inf)`, but I want to make sure that this is the behaviour we want: "If the year is in pds_adoption_limits but value is missing, cap at 0. If the year is not in pds_adoption_limits, do not cap"

## Next steps

I've reach a point where, even if more can be done with numpy (for instance in `customadoption._linear_forecast`), the bottleneck seems to be reading from csv.

It looks like when running all solutions with all scenarios, we end up opening 2000+ unique csvs 9000+ times in total. 

In profile results below, `parsers._read` which is used by pandas.read_csv is quite high up:

```
   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1708/1    0.009    0.000  210.889  210.889 {built-in method builtins.exec}
        1    0.032    0.032  210.889  210.889 time_all_solutions.py:1(<module>)
     1166    0.015    0.000   72.355    0.062 metaclass_cache.py:44(__call__)
   125664    0.510    0.000   63.980    0.001 indexing.py:665(__setitem__)
137519/125664    2.036    0.000   53.389    0.000 indexing.py:782(_setitem_with_indexer)
   143245    0.524    0.000   49.849    0.000 frame.py:414(__init__)
    27562    0.252    0.000   41.453    0.002 construction.py:213(init_dict)
468566/442826    2.390    0.000   30.964    0.000 series.py:183(__init__)
      144    0.002    0.000   29.393    0.204 adoptiondata.py:17(__init__)
      144    0.167    0.001   29.391    0.204 adoptiondata.py:48(_populate_adoption_data)
     9981    0.065    0.000   26.550    0.003 parsers.py:531(parser_f)
     9981    0.157    0.000   26.439    0.003 parsers.py:416(_read)
```

There would be several ways to tackle this. It looks like sometimes we process csvs in a similar way, for instance to build a new dictionary df_region of dataFrame structured per region - maybe we could have a preprocessing stage that we would run once and dump processed version of the data that could be read directly?

Alternatively / Additionally, we could cache the result of pd.read_csv the same way we do the metaclass_cache. I experimented with that here: https://github.com/klemag/solutions/tree/add_reader_cache - not sure if it's something we want though, for instance here I fail a test in vma that tries to reload csv from disk, is the app supposed to always read latest files or are files static?

### CODE REVIEW

**Comment by DentonGentry** [comment]
One followup note: these models may produce results which go in to future publications. I expect people who contribute to the software to be acknowledged. If you want to specify how the acknowledgement should read, please feel free to send a PR to add an entry to https://github.com/ProjectDrawdown/solutions/blob/master/.zenodo.json with institution, title, or other details you'd like to specify.

**Comment by DentonGentry** [comment]
Github never added you to https://github.com/ProjectDrawdown/solutions/graphs/contributors, and I don't understand why. Have you encountered this before?

Reading through https://stackoverflow.com/questions/40644933/not-showing-as-a-contributor-on-github doesn't list anything which seems relevant here.

If we can figure out why this happened (and it isn't something you've intentionally done for privacy) I'd be very motivated to correct it. I want people to get credit for their work.

**Comment by klemag** [comment]
Hi @DentonGentry , thanks for noticing and letting me know :)
That's odd, it looks like the commits were properly tagged on git, and they even show just fine on Github: https://github.com/ProjectDrawdown/solutions/commits/master?after=6ac7af5144ae6705284fbb3b7e01eb45da9d7e58+69
so I'd lean towards something with the way Github works out the list of contributors? I've got no idea what it can be though - I'll try to drop an email to Github support and see if they can help.

**Comment by DentonGentry** [comment]
It looks like the email to Github Support took care of it, you appear in https://github.com/ProjectDrawdown/solutions/graphs/contributors as of this morning.

**Comment by klemag** [comment]
Nice :) It was my bad actually - the email used on git commit wasn't verified with my Github account so apparently Github couldn't associate the two together.

**Pull request merged**
