### PR TITLE
Large-scale simplification.

### PR DESCRIPTION
**Pull request by glass-wing**
Rewrote loops to use vectorised operations and simplified.

### CODE REVIEW

**Comment by denised** [comment]
Fantastic to see @glass-wing !   Could you do me a favor and do a final merge with develop?

**Comment by glass-wing** [comment]
Thanks!
Not sure what you mean by a final merge though. The PR needs your
review/approval to complete.

N.

**Comment by denised** [comment]
Could you please do a merge from the develop branch of the repo, and fix any merge conflicts (if any occur) that result — thanks.  (You’ve got two merge commits in the pull request already, but the last was in November I think, and there have been code changes since)

-- 
  Denise Draper
  ***@***.***

**Comment by glass-wing** [comment]
ok got it - I've refreshed my personal fork with the latest code changes from the main repo. No merge conflicts.
Looks good now?

**Review by denised — APPROVED** [review]

**Comment by denised** [comment]
Great to see this in :-)

**Pull request merged**
